# Pacman pipeline

# Build and push the pacman image 
# deploy with helm on your kubernetes cluster 

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ContainerBuild@0
  displayName: "build pacman image"
  inputs:
    dockerRegistryServiceConnection: 'mcourcy-dockerhub'
    repository: 'michaelcourcy/pacman'
    Dockerfile: 'Dockerfile'
    # tag: $(Build.BuildId)

- task: KubectlInstaller@0
  displayName: "install kubectl"
  inputs:
    kubectlVersion: '1.26.1'

- task: Kubernetes@1
  displayName: "connect to pacman ns"
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'pacman-kasten-io-1679333939577'
    namespace: 'pacman'
    command: 'get'
    arguments: 'service'
    versionSpec: '1.26.1'

- task: Bash@3
  displayName: "backup pacman"
  inputs:
    targetType: 'inline'
    script: |
      cat <<EOF | kubectl create -f - 
              kind: BackupAction
              apiVersion: actions.kio.kasten.io/v1alpha1
              metadata:
                generateName: pacman-backupaction-
                namespace: pacman          
              spec:
                subject:
                  name: pacman
                  namespace: pacman
            EOF


# TODO wait for backupaction to complete instead of sleeping
# see an example in https://github.com/michaelcourcy/kasten-tekton/blob/main/tasks/backupaction-task.yml
- task: Bash@3
  displayName: "Wait for backup to complete"
  inputs:
    targetType: 'inline'
    script: 'sleep 300'


- task: HelmDeploy@0
  displayName: deploy pacman
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'pacman-kasten-io-1679333939577'
    namespace: 'pacman'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/pacman'
    releaseName: 'pacman'
    overrideValues: 'ingress.create=true,ingress.class=nginx,ingress.host=pacman.mcourcy.dev.azure.kasten.io,pacman.image.registry=docker.io,pacman.image.repository=michaelcourcy,pacman.image.image=pacman,pacman.image.tag=$(Build.BuildId)'

