# Pacman pipeline

# Build and push the pacman image 
# deploy with helm on your kubernetes cluster 

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: mcourcy-dockerhub
  registry: docker.io
  registry_user: michaelcourcy
  registry_repository: pacman
  kubernetesServiceEndpoint: mcourcy-cluster
  ingress: pacman.mcourcy.dev.azure.kasten.io

steps:
- task: ContainerBuild@0
  displayName: "build pacman image"
  inputs:
    dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
    repository: $(registry_user)/$(registry_repository)
    Dockerfile: 'Dockerfile'
    tag: $(Build.BuildId)

- task: Kubernetes@1
  displayName: "Backup before deploy"
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
    namespace: 'pacman'
    command: 'create'
    useConfigurationFile: true
    configuration: 'azuredevops/backupaction.yaml'


# TODO wait for backupaction to complete instead of sleeping
# see an example in https://github.com/michaelcourcy/kasten-tekton/blob/main/tasks/backupaction-task.yml
# probably need a dedicated Kasten task for backup action so 
# for the moment the simplest approach is just to wait 2 minutes 
# check this project https://github.com/Azure/k8s-set-context
- task: Bash@3
  displayName: "Wait for backup to complete"
  inputs:
    targetType: 'inline'
    script: |
            ls -al ~/.kube
            cat  ~/.kube/config
            export KUBECONFIG=~/.kube/config
            kubectl config get-contexts

- task: HelmDeploy@0
  displayName: deploy pacman
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: $(kubernetesServiceEndpoint)
    namespace: 'pacman'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/pacman'
    releaseName: 'pacman'
    overrideValues: 'ingress.create=true,ingress.class=nginx,ingress.host=$(ingress),pacman.image.registry=$(registry),pacman.image.repository=$(registry_user),pacman.image.image=$(registry_repository),pacman.image.tag=$(Build.BuildId)'

