# Pacman pipeline

# Build and push the pacman image 
# deploy with helm on your kubernetes cluster 

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ContainerBuild@0
  displayName: "build pacman image"
  inputs:
    dockerRegistryServiceConnection: 'mcourcy-dockerhub'
    repository: 'michaelcourcy/pacman'
    Dockerfile: 'Dockerfile'
    # tag: $(Build.BuildId)


- task: HelmDeploy@0
  displayName: deploy pacman
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'pacman-kasten-io-1679333939577'
    namespace: 'pacman'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/pacman'
    releaseName: 'pacman'
    overrideValues: 'ingress.create=true,ingress.class=nginx,ingress.host=pacman.mcourcy.dev.azure.kasten.io,pacman.image.registry=docker.io,pacman.image.repository=michaelcourcy,pacman.image.image=pacman,pacman.image.tag=$(Build.BuildId)'

