# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ContainerBuild@0
  inputs:
    dockerRegistryServiceConnection: 'mcourcy-dockerhub'
    repository: 'michaelcourcy/pacman'
    Dockerfile: 'Dockerfile'
    # tag: $(Build.BuildId)

- task: HelmInstaller@0
  inputs:
    helmVersion: '3.11.0'
    installKubectl: true
    kubectlVersion: '1.26.1'
    checkLatestKubectl: false

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'pacman-kasten-io-1679333939577'
    namespace: 'pacman'
    command: 'get'
    arguments: 'serviceaccount'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
