apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backupaction.serviceAccountName" . }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kastenRelease }}-basic
subjects:
- kind: ServiceAccount
  name: {{ include "backupaction.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}